enhancement:
  - "features/*"
  - "feature/*"
  - "feat/*"
  - "features-*"
  - "feature-*"
  - "feat-*"
bug:
  - "fixes/*"
  - fix/*"
chore:
  - "chore/*"
  - "update/*"
dependencies:
  - "update/*"
