[tool.black]
line-length = 99
target-version = ["py27"]
force-exclude = """
Assets/Python/data/maps/
"""

[tool.ruff]
select = [
  # pycodestyle
  "E",
  # pyflakes
  "F",
]
ignore = [
  "E501",
  "F841", # unused variables are okay
  "F403", # star imports are okay
  "F405", # star imports are okay
]
extend-exclude = ["Docs/Tools/*.py", "Assets/Python/data/maps/*.py"]
target-version = "py37"

[tool.pyright]
executionEnvironments = [
  { pythonVersion = "2.4", root = "Assets/Python", extraPaths = [
    # Folders of the project
    "Assets/Python/",
    "Assets/Python/data",
    "Assets/Python/data/maps",
    "Assets/Python/utils",
    "Assets/Python/models",
    "Assets/Python/components",
    "Assets/Python/EntryPoints",
    "Assets/Python/pyWB",
    "Assets/Python/screens",
    # Folders from Sid Meier's Civilization IV Beyond the Sword/Beyond the Sword/Assets/Python
    "../../Assets/Python",
    "../../Assets/Python/EntryPoints",
    "../../Assets/Python/pyWB",
    "../../Assets/Python/Screens",
    "../../Assets/Python/pyUnit",
    "../../Assets/Python/pyHelper",
    "../../Assets/Python/PitBoss",
    # Folders from Sid Meier's Civilization IV Beyond the Sword/Assets/Python
    "../../../Assets/Python/pyHelper",
  ] },
]
stubPath = "Assets/Python/.stubs"
reportMissingModuleSource = false
reportGeneralTypeIssues = false
reportMissingImports = false
typeCheckingMode = "off"
exclude = [
  "Assets/Python/EntryPoints/CvScreensInterface.py",
  "Assets/Python/screens/CvWorldBuilderScreen.py",
  "Assets/Python/pyWB/CvWBDesc.py",
  "Assets/Python/PyHelpers.py",
]
