# Build DLL if changes apply on the CvGameCoreDLL folder
name: Build DLL

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Install build dependencies
        run: |
          Invoke-WebRequest http://kael.civfanatics.net/files/VCToolkitSetup.exe -OutFile ${env:TEMP}\VCToolkitSetup.exe
          & ${env:TEMP}\VCToolkitSetup.exe /s /v"/qb"
          Start-Sleep -s 120
          Invoke-WebRequest http://kael.civfanatics.net/files/msvcrt.lib -OutFile "C:\Program Files (x86)\Microsoft Visual C++ Toolkit 2003\lib\msvcrt.lib"
          Invoke-WebRequest http://kael.civfanatics.net/files/msvcrtd.lib -OutFile "C:\Program Files (x86)\Microsoft Visual C++ Toolkit 2003\lib\msvcrtd.lib"
          Invoke-WebRequest http://kael.civfanatics.net/files/msvcprt.lib -OutFile "C:\Program Files (x86)\Microsoft Visual C++ Toolkit 2003\lib\msvcprt.lib"
      - name: Build DLL
        run: msbuild CvGameCoreDLL\CvGameCoreDLL.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CvGameCoreDLL
          path: Assets/CvGameCoreDLL.dll
