# Apply linting and testing
name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 2.4
        run: |
          curl -LO https://www.python.org/ftp/python/2.4/Python-2.4.tar.bz2
          bzcat Python-2.4.tar.bz2 | tar -xf -
          cd Python-2.4
          ./configure
          make
          make install
      - name: Run tests
        run: |
          make test
